name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Setup pnpm
        run: npm i -g pnpm@9

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm --filter api build
          pnpm --filter web build

      - name: Upload build to server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude ".git" --exclude "node_modules"
          path: .
          remote_path: /var/www/shop-platform
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: deploy
          remote_key: ${{ secrets.VPS_SSH_KEY }}

      - name: Restart services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/shop-platform
            pnpm install --frozen-lockfile
            cd apps/api && pnpm prisma migrate deploy && cd ../../
            pm2 reload shop-api || pm2 start apps/api/dist/src/server.js --name shop-api
            pm2 reload shop-web || pm2 start "pnpm --filter web start" --name shop-web
            pm2 save
